In [2]:
pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\suriy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

In [4]:
titanic = pd.read_csv("titanic.csv")
students = pd.read_csv("StudentsPerformance.csv")

In [5]:
titanic.head()
titanic.tail()
students.head()
students.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
titanic.info()
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [7]:
titanic.describe()
students.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [8]:
titanic_features = {
    "Numerical": ["Age", "Fare", "SibSp", "Parch"],
    "Categorical": ["Sex", "Embarked", "Ticket", "Cabin", "Name"],
    "Ordinal": ["Pclass"],
    "Binary": ["Survived"]
}

students_features = {
    "Numerical": ["math score", "reading score", "writing score"],
    "Categorical": ["gender", "race/ethnicity", "parental level of education"],
    "Binary": ["lunch", "test preparation course"]
}

titanic_features, students_features

({'Numerical': ['Age', 'Fare', 'SibSp', 'Parch'],
  'Categorical': ['Sex', 'Embarked', 'Ticket', 'Cabin', 'Name'],
  'Ordinal': ['Pclass'],
  'Binary': ['Survived']},
 {'Numerical': ['math score', 'reading score', 'writing score'],
  'Categorical': ['gender', 'race/ethnicity', 'parental level of education'],
  'Binary': ['lunch', 'test preparation course']})

In [9]:
titanic["Sex"].unique()
titanic["Embarked"].unique()
students["gender"].unique()
students["lunch"].unique()

array(['standard', 'free/reduced'], dtype=object)

In [10]:
X_titanic = titanic.drop("Survived", axis=1)
y_titanic = titanic["Survived"]

X_students = students.drop("math score", axis=1)
y_students = students["math score"]

In [11]:
titanic.shape
students.shape

(1000, 8)

In [12]:
titanic.isnull().sum()
students.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64